### ISSUE TITLE
Bad decrypt issue when downloading files

### ISSUE THREAD

**Issue by phutchins** [Storj/metadisk-client#16]
When downloading a file from the api, I occasionally see an error decrypting.
- Bad Decrypt
  When downloading a file directly from one of the API hosts behind the balancer, I'm getting the following error... I am sometimes able to download the file successfully however.

```
$ storjcli -u http://api1.storj.io:8080 downloadfile [my_bucket_id] [my_file_id] ./downloadedfile.9
 [info]   Received 65536 bytes of data
 [info]   Received 65536 bytes of data
 [info]   Received 65536 bytes of data
 [info]   Received 65536 bytes of data
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at DecryptStream.Cipher._flush (crypto.js:128:28)
    at DecryptStream.<anonymous> (_stream_transform.js:118:12)
    at DecryptStream.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DecryptStream.emit (events.js:179:7)
    at prefinish (_stream_writable.js:468:12)
    at finishMaybe (_stream_writable.js:476:7)
    at endWritable (_stream_writable.js:488:3)
    at DecryptStream.Writable.end (_stream_writable.js:453:5)
```

**Comment by 161chihuahuas** [comment]
The file crypto has been completely reworked here: https://github.com/Storj/core/pull/115

Will leave this open until that is merged so it can be checked.

**Comment by 161chihuahuas** [comment]
My tests against bridge 0.8.0 (not yet released) and the latest bridge-client with core 1.0.0 indicate this is no longer a problem.
